f=imread('475x630 ali nice.png');
f=rgb2gray(f);
g_gaussian=imnoise(f,'gaussian');
g_salt=imnoise(f,'salt & pepper');
% figure(1),imshow(f);
figure(2),imshow(g_gaussian);
% figure(3),imshow(g_salt);
g_salt_min=ordfilt2(g_salt,1,ones(3,3));
g_salt_max=ordfilt2(g_salt,9,ones(3,3));
g_salt_median=ordfilt2(g_salt,5,ones(3,3));
% figure(4),imshow(g_salt_min);
% figure(5),imshow(g_salt_max);
% figure(6),imshow(g_salt_median); 
g_guassian_min=ordfilt2(g_gaussian,1,ones(3,3));
g_guassian_max=ordfilt2(g_gaussian,9,ones(3,3));
g_guassian_median=ordfilt2(g_gaussian,5,ones(3,3));
% figure(7),imshow(g_guassian_min);
% figure(8),imshow(g_guassian_max);
figure(9),imshow(g_guassian_median);