%  f=[1 2 3;
%    4 5 6;
%    7 8 9];
f=imread('450x340 two man wearing black cote.png');
f=rgb2gray(f);
f=double(f);
laplacian=fspecial('laplacian',0);
prewitt1=fspecial('prewitt');
prewitt2=prewitt1';
sobel1=fspecial('sobel');
sobel2=sobel1';
robert1=[-1 0;
          0 1];
robert2=[ 0 1;
         -1 0];
g_laplacian=imfilter(f,laplacian,'corr','circular','same');
g_laplacian=mat2gray(g_laplacian)*9;
g_sobel1=imfilter(f,sobel1,'corr','circular','same');
g_sobel2=imfilter(f,sobel2,'corr','circular','same');
g_soble=((g_sobel1).^2+(g_sobel2).^2).^(1/2);
g_soble=ceil(g_soble);
g_prewitt1=imfilter(f,prewitt1,'corr','circular','same');
g_prewitt2=imfilter(f,prewitt2,'corr','circular','same');
g_prewitt=((g_prewitt1).^2+(g_prewitt2).^2).^(1/2);
g_prewitt=ceil(g_prewitt);
g_robert1=imfilter(f,robert1,'corr','circular','same');
g_robert2=imfilter(f,robert2,'corr','circular','same');
g_robert=((g_robert1).^2+(g_robert2).^2).^(1/2);
g_robert=ceil(g_robert);
figure(1),imshow(g_laplacian,[]);
figure(2),imshow(g_soble,[]);
figure(3),imshow(g_robert,[]);
figure(4),imshow(g_prewitt,[]);